### ISSUE TITLE
Suddenly stopped working in 10.2

### ISSUE THREAD

**Issue by rugelly** [dekallo/HideButtonGlow#6]
Debug mode says it is hiding the proper glows at the proper times, but the glow is not actually being hidden. This started happening in 10.2.
Using default blizz bars

Tried using "hide all" mode, same result.
Reset WTF folder, same result.

Anything else I could try to problem solve this?

**Comment by ntowle** [comment]
Can you confirm if you are running v27? And are the spells which are not hiding macros or regular spells?

**Comment by rugelly** [comment]
Can confirm v27, and spells are freshly dragged out of spellbook onto bar

**Comment by ntowle** [comment]
Can you install v26 and let me know if you have the same problem? It seems to be working fine for me on v27 with the default Blizzard bars.

Maybe these would help too:
1. What class/spec/spell?
2. Can you post a screenshot showing your bars glowing + the filter match message from debug mode?

**Comment by rugelly** [comment]
![ui](https://github.com/dekallo/HideButtonGlow/assets/52133943/61c5d8de-e360-4a02-8b98-a0ee7ba69691)

Enhance shaman, blizz has these glow at 5 stacks of maelstrom which is pretty dang annoying since they can go up to 10!

**Comment by ntowle** [comment]
Thanks for the info, so it's not working for you on v26 or v27.

Can you disable all other addons besides HideButtonGlow and see if it works then? I'm thinking it could be a compatibility issue with another addon.

For what it's worth it's working on my Enhance Shaman:
![image](https://github.com/dekallo/HideButtonGlow/assets/20693723/dd320e94-ee4b-4d22-94ff-6ab1bf0e808c)

But I noticed my glow effect looks a little different from yours, thinking that could be related.

**Comment by rugelly** [comment]
Ah... I feel so dumb now. The culprit is [HideActionbarAnimations](https://www.curseforge.com/wow/addons/hideactionbaranimations)

Downgrading BOTH addons to 10.1.7 works properly, however if EITHER/BOTH addon(s) are a newer version then your addon doesn't work properly.

Ill have to fiddle with the other addon

Thanks for your time

extra update: it was a simple as setting hideAnims to use the 'new' button glow

**Comment by ntowle** [comment]
Ah it looks like HideActionbarAnimations when set to use the old glow now creates their own custom glow frame `HideActionbarAnimations_SpellActivationAlert` which HideButtonGlow doesn't know to look for.

As to why HideButtonGlow v27 is no longer compatible with the previous version of HideActionbarAnimations, it was because HideActionbarAnimations used to create a glow frame called `overlay` which had the same name as the old Blizzard glow frame (removed in 10.0.2, Dragonflight pre-patch), which HideButtonGlow was still checking for until v27. I removed the check for that if Blizzard's new glow frame can be found since they wouldn't normally both exist at the same time.

Seems like you found the best solution though, to disable the custom glow frame created by HideActionbarAnimations.
